// Test definitions. Do NOT edit this file!
#define CATCH_CONFIG_MAIN
#include "catch.hpp"
#include "main.hpp"

// ─────────────────────────────────────────────────────────────────────────────
// [T1]  bubble() — one pass on known input
// ─────────────────────────────────────────────────────────────────────────────

TEST_CASE("T1a: bubble pass on [8,4,2,1,10] -> [4,2,1,8,10]", "[T1]")
{
    vector<int> v = {8, 4, 2, 1, 10};
    bubble(v);
    vector<int> exp = {4, 2, 1, 8, 10};
    REQUIRE(v == exp);
}

TEST_CASE("T1b: bubble pass on [9,3,7,1,5] -> max 9 lands at last index", "[T1]")
{
    vector<int> v = {9, 3, 7, 1, 5};
    bubble(v);
    REQUIRE(v.back() == 9);
}

// ─────────────────────────────────────────────────────────────────────────────
// [T2]  bubble() — already-sorted and reverse-sorted inputs
// ─────────────────────────────────────────────────────────────────────────────

TEST_CASE("T2a: bubble pass on already-sorted array leaves it unchanged", "[T2]")
{
    vector<int> v = {1, 2, 3, 4, 5};
    vector<int> orig = v;
    bubble(v);
    REQUIRE(v == orig);
}

TEST_CASE("T2b: bubble pass on reverse-sorted [5,4,3,2,1] — max bubbles to end", "[T2]")
{
    vector<int> v = {5, 4, 3, 2, 1};
    bubble(v);
    REQUIRE(v.back() == 5);
}

// ─────────────────────────────────────────────────────────────────────────────
// [T3]  bubblesort() — full sort via N-1 bubble passes
// ─────────────────────────────────────────────────────────────────────────────

TEST_CASE("T3a: bubblesort sorts [64,34,25,12,22,11,90] ascending", "[T3]")
{
    vector<int> v = {64, 34, 25, 12, 22, 11, 90};
    bubblesort(v);
    vector<int> exp = {11, 12, 22, 25, 34, 64, 90};
    REQUIRE(v == exp);
}

TEST_CASE("T3b: bubblesort sorts reverse-sorted vector", "[T3]")
{
    vector<int> v = {99, 80, 60, 40, 20, 10, 5, 1};
    bubblesort(v);
    vector<int> exp = {1, 5, 10, 20, 40, 60, 80, 99};
    REQUIRE(v == exp);
}

// ─────────────────────────────────────────────────────────────────────────────
// [T4]  Edge cases — small / uniform / random vectors
// ─────────────────────────────────────────────────────────────────────────────

TEST_CASE("T4a: bubblesort on single-element vector leaves it unchanged", "[T4]")
{
    vector<int> v = {7};
    bubblesort(v);
    REQUIRE(v.size() == 1);
    REQUIRE(v[0] == 7);
}

TEST_CASE("T4b: bubblesort on all-equal vector leaves it unchanged and sorted", "[T4]")
{
    vector<int> v = {5, 5, 5, 5, 5};
    bubblesort(v);
    for (size_t i = 1; i < v.size(); i++)
        REQUIRE(v[i - 1] <= v[i]);
    REQUIRE(v[0] == 5);
    REQUIRE(v.back() == 5);
}
